apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- increase-replicas.yaml

spec:
  containers:
    - name: demoproj
      image: dhpup/demoproj