name: demoproj

on:
  push:
    paths-ignore:
      - '**/kustomization.yaml'
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: dhpup/demoproj
          tags: |
            type=sha
          # type=schedule
          # type=ref,event=branch
          # type=ref,event=pr
          # type=semver,pattern={{version}}
          # type=semver,pattern={{major}}.{{minor}}
          # type=semver,pattern={{major}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        uses: imranismail/setup-kustomize@v1
      - 
        name: Kustomize
        run: |
          cd demoproj/env/stage
          kustomize edit set image ${{ steps.meta.outputs.tags }}
          git config --global user.name "Commit Bot"
          git config --global user.email "no-reply@akuity.io"
          git add .
          git commit -m "Set dhpup/demoproj image tag to ${{ steps.meta.outputs.tags }}"
          git push
